#!/bin/sh

[ -f "/www/luci-static/resources/icons/loading.gif" ] && \
	sed -i "s,/loading.svg,/loading.gif,g" "/www/luci-static/resources/view/hongshuyun/status.js"

uci -q batch <<-EOF >"/dev/null"
	delete firewall.hongshuyun_pre

	delete firewall.hongshuyun_forward
	set firewall.hongshuyun_forward=include
	set firewall.hongshuyun_forward.type=nftables
	set firewall.hongshuyun_forward.path="/var/run/hongshuyun/fw4_forward.nft"
	set firewall.hongshuyun_forward.position="chain-pre"
	set firewall.hongshuyun_forward.chain="forward"

	delete firewall.hongshuyun_input
	set firewall.hongshuyun_input=include
	set firewall.hongshuyun_input.type=nftables
	set firewall.hongshuyun_input.path="/var/run/hongshuyun/fw4_input.nft"
	set firewall.hongshuyun_input.position="chain-pre"
	set firewall.hongshuyun_input.chain="input"

	delete firewall.hongshuyun_post
	set firewall.hongshuyun_post=include
	set firewall.hongshuyun_post.type=nftables
	set firewall.hongshuyun_post.path="/var/run/hongshuyun/fw4_post.nft"
	set firewall.hongshuyun_post.position="table-post"
	commit firewall
EOF

if [ -f "/etc/init.d/hongshuyun" ]; then
	/etc/init.d/hongshuyun stop >/dev/null 2>&1
fi

rm -rf /var/run/hongshuyun >/dev/null 2>&1

rm -f /etc/config/hongshuyun /etc/config/hongshuyun-opkg >/dev/null 2>&1
if [ -f "/usr/share/hongshuyun/defaults/hongshuyun" ]; then
	cp -f /usr/share/hongshuyun/defaults/hongshuyun /etc/config/hongshuyun
fi

if [ -f "/etc/crontabs/root" ]; then
	sed -i '/hongshuyun\/scripts\/update_crond\.sh/d' /etc/crontabs/root
fi

/etc/init.d/cron restart >/dev/null 2>&1

rm -f /tmp/luci-indexcache*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

exit 0
