#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2022-2023 ImmortalWrt.org

USE_PROCD=1

START=99
STOP=10

CONF="hongshuyun"
PROG="/usr/bin/sing-box"

HP_DIR="/etc/hongshuyun"
RUN_DIR="/var/run/hongshuyun"
LOG_PATH="$RUN_DIR/hongshuyun.log"

# we don't know which is the default server, just take the first one
DNSMASQ_UCI_CONFIG="$(uci -q show "dhcp.@dnsmasq[0]" | awk 'NR==1 {split($0, conf, /[.=]/); print conf[2]}')"
if [ -f "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG" ]; then
	DNSMASQ_DIR="$(awk -F '=' '/^conf-dir=/ {print $2}' "/tmp/etc/dnsmasq.conf.$DNSMASQ_UCI_CONFIG")/dnsmasq-hongshuyun.d"
else
	DNSMASQ_DIR="/tmp/dnsmasq.d/dnsmasq-hongshuyun.d"
fi

log() {
	echo -e "$(date "+%Y-%m-%d %H:%M:%S") [DAEMON] $*" >> "$LOG_PATH"
}

start_service() {
	config_load "$CONF"

	local outbound_node
	config_get outbound_node "config" "main_node" "nil"
	if [ "$outbound_node" = "nil" ]; then
		return 1
	fi

	mkdir -p "$RUN_DIR"

	# Generate/Validate client config
	ucode -S "$HP_DIR/scripts/generate_client.uc" 2>>"$LOG_PATH"

	if [ ! -e "$RUN_DIR/sing-box-c.json" ]; then
		log "Error: failed to generate client configuration."
		return 1
	elif ! "$PROG" check --config "$RUN_DIR/sing-box-c.json" 2>>"$LOG_PATH"; then
		log "Error: wrong client configuration detected."
		return 1
	fi

	# DNSMasq rules
	local ipv6_support dns_port
	config_get_bool ipv6_support "config" "ipv6_support" "0"
	config_get dns_port "infra" "dns_port" "5333"
	mkdir -p "$DNSMASQ_DIR"
	echo -e "conf-dir=$DNSMASQ_DIR" > "$DNSMASQ_DIR/../dnsmasq-hongshuyun.conf"
	cat <<-EOF >> "$DNSMASQ_DIR/redirect-dns.conf"
		no-poll
		no-resolv
		server=127.0.0.1#$dns_port
	EOF
	/etc/init.d/dnsmasq restart >"/dev/null" 2>&1

	# Setup routing table (UDP TProxy)
	local table_mark tproxy_mark
	config_get table_mark "infra" "table_mark" "100"
	config_get tproxy_mark "infra" "tproxy_mark" "101"

	ip rule add fwmark "$tproxy_mark" table "$table_mark"
	ip route add local 0.0.0.0/0 dev lo table "$table_mark"
	if [ "$ipv6_support" -eq "1" ]; then
		ip -6 rule add fwmark "$tproxy_mark" table "$table_mark"
		ip -6 route add local ::/0 dev lo table "$table_mark"
	fi

	# sing-box (client)
	procd_open_instance "sing-box-c"

	procd_set_param command "$PROG"
	procd_append_param command run --config "$RUN_DIR/sing-box-c.json"

	# QUIC-GO GSO is broken on kernel 6.6 currently
	uname -r | grep -Eq "^6\.6" && procd_set_param env "QUIC_GO_DISABLE_GSO"="true"

	if [ -x "/sbin/ujail" ] && ! grep -Eq '"type": "(wireguard|tun)"' "$RUN_DIR/sing-box-c.json"; then
		procd_add_jail "sing-box-c" log procfs
		procd_add_jail_mount "$RUN_DIR/sing-box-c.json"
		procd_add_jail_mount_rw "$RUN_DIR/sing-box-c.log"
		procd_add_jail_mount "$HP_DIR/certs/"
		procd_add_jail_mount "/etc/ssl/"
		procd_add_jail_mount "/etc/localtime"
		procd_add_jail_mount "/etc/TZ"
		procd_set_param capabilities "/etc/capabilities/hongshuyun.json"
		procd_set_param no_new_privs 1
		procd_set_param user sing-box
		procd_set_param group sing-box
	fi

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param stderr 1
	procd_set_param respawn

	procd_close_instance

	# log-cleaner
	procd_open_instance "log-cleaner"
	procd_set_param command "$HP_DIR/scripts/clean_log.sh"
	procd_set_param respawn
	procd_close_instance

	[ "$outbound_node" = "nil" ] || echo > "$RUN_DIR/sing-box-c.log"

	# Update permissions for ujail
	chown -R sing-box:sing-box "$RUN_DIR"

	# Setup firewall
	ucode "$HP_DIR/scripts/firewall_pre.uc"
	[ "$outbound_node" = "nil" ] || utpl -S "$HP_DIR/scripts/firewall_post.ut" > "$RUN_DIR/fw4_post.nft"
	fw4 reload >"/dev/null" 2>&1

	log "sing-box $(sing-box version -n) started."
}

stop_service() {
	# Setup firewall
	# Load config
	config_load "$CONF"
	local table_mark tproxy_mark
	config_get table_mark "infra" "table_mark" "100"
	config_get tproxy_mark "infra" "tproxy_mark" "101"

	# Tproxy
	ip rule del fwmark "$tproxy_mark" table "$table_mark" 2>"/dev/null"
	ip route del local 0.0.0.0/0 dev lo table "$table_mark" 2>"/dev/null"
	ip -6 rule del fwmark "$tproxy_mark" table "$table_mark" 2>"/dev/null"
	ip -6 route del local ::/0 dev lo table "$table_mark" 2>"/dev/null"

	# Nftables rules
	for i in "hongshuyun_redirect" "hongshuyun_mangle_prerouting"; do
		nft flush chain inet fw4 "$i"
		nft delete chain inet fw4 "$i"
	done 2>"/dev/null"
	for i in "hongshuyun_local_addr_v4" "hongshuyun_local_addr_v6" \
		 "hongshuyun_mainland_addr_v4" "hongshuyun_mainland_addr_v6"; do
		nft flush set inet fw4 "$i"
		nft delete set inet fw4 "$i"
	done 2>"/dev/null"
	echo 2>"/dev/null" > "$RUN_DIR/fw4_forward.nft"
	echo 2>"/dev/null" > "$RUN_DIR/fw4_input.nft"
	echo 2>"/dev/null" > "$RUN_DIR/fw4_post.nft"
	fw4 reload >"/dev/null" 2>&1

	# Remove DNS hijack
	rm -rf "$DNSMASQ_DIR/../dnsmasq-hongshuyun.conf" "$DNSMASQ_DIR"
	/etc/init.d/dnsmasq restart >"/dev/null" 2>&1

	rm -f "$RUN_DIR/sing-box-c.json" "$RUN_DIR/sing-box-c.log"

	log "Service stopped."
}

reload_service() {
	log "Reloading service..."

	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
	procd_add_interface_trigger "interface.*.up" wan /etc/init.d/$CONF reload
}
